### ISSUE TITLE
Rxjs dependency

### ISSUE THREAD

**Issue by klaascuvelier** [AntJanus/angular2-ts-starter-kit#1]
When trying to use your starter kit, I ran into troubles when running `gulp` to start the server:

``` bash


ERROR in node_modules/angular2/src/facade/async.d.ts
(3,25): error TS2307: Cannot find module 'rxjs/Subject'.

ERROR in node_modules/angular2/src/facade/async.d.ts
(4,44): error TS2307: Cannot find module 'rxjs/Observable'.

ERROR in node_modules/angular2/src/facade/async.d.ts
(5,26): error TS2307: Cannot find module 'rxjs/Operator'.

ERROR in node_modules/angular2/src/facade/async.d.ts
(6,25): error TS2307: Cannot find module 'rxjs/Subject'.

ERROR in ./~/angular2/src/facade/async.js
Module not found: Error: Cannot resolve module 'rxjs/Subject' in /node_modules/angular2/src/facade
 @ ./~/angular2/src/facade/async.js 10:16-39 14:16-39

ERROR in ./~/angular2/src/facade/async.js
Module not found: Error: Cannot resolve module 'rxjs/Observable' in /node_modules/angular2/src/facade
 @ ./~/angular2/src/facade/async.js 11:19-45

```

I found out it could be solved by just npm installing rxjs.
I am not sure if this is because of the newer version from Angular2? Or Why I have this problem

**Comment by AntJanus** [comment]
RXjs installs automatically with Angular 2 so I find it strange that you'd have to install it separately. I tested all the code with `alpha-52`, blowing away all the node_modules and reinstalling them. Can you tell me your process for running the app?

Oh and what version of Node/NPM are you running? Maybe that'll answer some of the questions.

**Comment by klaascuvelier** [comment]
You're correct, it's NPM. 
On version 2, It's installed, but when using version 3 (my default) it is not there.
Not sure how it happens, some issue with the flat tree I guess.

I suppose this one can be closed, I'd rather should file an issue at NPM

**Comment by AntJanus** [comment]
Ahhh crap, I use NPM 2 as well so I wouldn't know about NPM 3. But I'll look into it when I have a chance.

**Comment by klaascuvelier** [comment]
If it's NPM related, I don't think there is much you can do. :)
The dependency is indeed specified in the angular package.json, so NPM should resolve it.

**Comment by AntJanus** [comment]
@klaascuvelier if you can either submit that issue to angular/angular or npm that'd be stellar! And let me know where it's at, I'll subscribe and follow it. In the meantime, I don't entirely feel comfortable merging your solution in since whenever I'll want to upgrade Angular 2, I'll have to check their Rx version.
